-- MySQL Script generated by MySQL Workbench
-- Qui 01 Jun 2017 17:17:45 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema posweb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `posweb` ;

-- -----------------------------------------------------
-- Schema posweb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `posweb` DEFAULT CHARACTER SET utf8 ;
USE `posweb` ;

-- -----------------------------------------------------
-- Table `posweb`.`contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posweb`.`contato` (
  `contact_id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `idade` INT(11) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `sobrenome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`contact_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `posweb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posweb`.`user` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `posweb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posweb`.`roles` (
  `role_id` INT(11) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `posweb`.`user_has_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `posweb`.`user_has_roles` (
  `user_id` INT(11) NOT NULL,
  `user_profile_role_id` INT(11) NOT NULL,
  PRIMARY KEY (`user_id`, `user_profile_role_id`),
  INDEX `fk_tb_usuario_has_user_profile_user_profile1_idx` (`user_profile_role_id` ASC),
  INDEX `fk_tb_usuario_has_user_profile_tb_usuario_idx` (`user_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

